services:
  app:
    container_name: nestjs_container
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    command: npm run start:dev
    ports:
      - 4000:4000
    environment:
      DATABASE_URL: postgresql://postgres:123@postgres:5432/nestjs?schema=public&connect_timeout=300
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  postgres:
    container_name: postgres_container
    build:
      context: .
      dockerfile: ./src/config/Dockerfile
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - /var/lib/postgresql/data