version: "3.8"
services:
  ivashinserver:
    depends_on:
      - db
    build:
      context: ./
    image: ivashinserver:latest
    ports:
      - "5000:5000"
    networks:
      main2:
    hostname: "ivashinserver.local"
    container_name: "ivashinserver"
    command: "npm run start"

  db:
    image: library/postgres:15
    hostname: "db.local"
    networks:
      main2:
    container_name: db
    env_file:
      - ./.env
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    env_file:
      - ./.env
    ports:
      - "3002:80"
    networks:
      main2:

networks:
  main2: